###Get Temperatures Ok
GET https://go-temppc-jqgf4k663q-uc.a.run.app/temperature/59090050 HTTP/1.1
Content-Type: application/json


####

###Get Temperatures 404 [can not find zipcode]
GET https://go-temppc-jqgf4k663q-uc.a.run.app/temperature/11111111 HTTP/1.1
Content-Type: application/json

####

###Get Temperatures 422 [invalid zipcode]
GET https://go-temppc-jqgf4k663q-uc.a.run.app/temperature/124ABC HTTP/1.1
Content-Type: application/json